name: doctor_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  bloc: ^8.1.3
  built_value: ^8.9.1
  cloud_firestore: ^4.14.0
  equatable: ^2.0.5
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_form_builder: ^9.2.1
  fluttertoast: ^8.2.4
  get_it: ^7.6.7
  intl: ^0.19.0
  json_serializable: ^6.7.1
  sticky_grouped_list: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  cupertino_icons: ^1.0.2
  build_runner: ^2.4.8
  built_value_generator: ^8.9.1


flutter:
  uses-material-design: true
